### ISSUE TITLE
Makefile content depends something that you have

### ISSUE THREAD

**Issue by FoxieFlakey** [lazear/ext2-boot#2]
Like
`/home/lazear/opt/cross/bin/i686-elf-gcc`, `../ext2util/ext2util`, and `/home/lazear/opt/cross/bin/i686-elf-gcc` please make it can be used without changing that

**Comment by ghost** [comment]
Maybe you should change it yourself for your needs and follow directions.

**Comment by lazear** [comment]
I evidently missed the first notification of the issue. As you can see, the repo hasn't been updated in > 5 years - if you'd like to make a pull request, I'm happy to merge it - otherwise I will close :)

**Comment by FoxieFlakey** [comment]
ok thanks
![fundyHappy](https://user-images.githubusercontent.com/67861857/183377454-144a0b32-56cd-45c8-9156-5de4f8afad6d.png)
